### ISSUE TITLE
Stylelint error

### ISSUE THREAD

**Issue by weebao** [kutsan/stylelint-config-clean-order#32]
```
Error: stylelint requires plugins to expose a ruleName. The plugin "C:\Users\username\code\node_modules\stylelint-config-clean-order\warning.js" is not doing this, so will not work with stylelint. Please file an issue with the plugin.
    at configurationError (file:///C:/Users/username/code/node_modules/stylelint/lib/utils/configurationError.mjs:12:49)
    at addPluginFunctions (file:///C:/Users/username/code/node_modules/stylelint/lib/augmentConfig.mjs:342:11)
    at async augmentConfigFull (file:///C:/Users/username/code/node_modules/stylelint/lib/augmentConfig.mjs:121:20)
    at async search (C:\Users\username\code\node_modules\stylelint\node_modules\cosmiconfig\dist\Explorer.js:53:36)
    at async search (C:\Users\username\code\node_modules\stylelint\node_modules\cosmiconfig\dist\Explorer.js:71:28)
    at async search (C:\Users\username\code\node_modules\stylelint\node_modules\cosmiconfig\dist\Explorer.js:71:28)
    at async search (C:\Users\username\code\node_modules\stylelint\node_modules\cosmiconfig\dist\Explorer.js:71:28)
    at async Explorer.search (C:\Users\username\code\node_modules\stylelint\node_modules\cosmiconfig\dist\Explorer.js:78:20)
    at async getConfigForFile (file:///C:/Users/username/code/baodang-portfolio/node_modules/stylelint/lib/getConfigForFile.mjs:59:5)
    at async isPathIgnored (file:///C:/Users/username/code/baodang-portfolio/node_modules/stylelint/lib/isPathIgnored.mjs:23:17)
 ```

Does anyone know how to deal with this?

**Comment by kutsan** [comment]
I'm assuming you've added `stylelint-config-clean-order` to `"plugins"` section of stylelintrc file but it should be in `"extends"`.

**Comment by kutsan** [comment]
I'm closing the issue, but if the problem still persists, please let me know.
